SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, 
    (SELECT ROUND(AVG(REVIEW_SCORE), 2) 
     FROM REST_REVIEW
     WHERE REST_REVIEW.REST_ID = REST_INFO.REST_ID
    ) AS SCORE
FROM REST_INFO
WHERE ADDRESS LIKE '서울%'
AND REST_ID IN (
    SELECT REST_ID
    FROM REST_REVIEW
)
ORDER BY SCORE DESC, FAVORITES DESC;