SELECT 
    (SELECT TITLE 
     FROM USED_GOODS_BOARD
     WHERE USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID)
     AS TITLE, BOARD_ID, REPLY_ID, WRITER_ID, CONTENTS, CREATED_DATE
FROM USED_GOODS_REPLY
WHERE BOARD_ID 
IN (SELECT BOARD_ID 
    FROM USED_GOODS_BOARD
    WHERE DATE(CREATED_DATE) BETWEEN '2022-10-01' AND '2022-10-31')
ORDER BY CREATED_DATE, TITLE